In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
from sklearn.datasets import load_wine
dataset=load_wine()

In [2]:
dataset.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [11]:
print(dataset.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [8]:
dataset['data'][:2]

array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03]])

In [9]:
dataset['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
from sklearn.preprocessing import StandardScaler


In [12]:
X=dataset['data']
y=dataset['target']

In [36]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
X_scaled=SS.fit_transform(X)

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X_scaled,y,test_size=0.4)

In [38]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()


In [39]:
from sklearn.svm import SVC
svm=SVC()

In [40]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()

In [41]:
from sklearn.model_selection import cross_val_score
C_V_L=cross_val_score(lr,X_train,Y_train,cv=5)
C_V_svm=cross_val_score(svm,X_train,Y_train,cv=5)
C_V_knn=cross_val_score(knn,X_train,Y_train,cv=5)


D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to

In [42]:
print(C_V_L) #overfitting

[1.         0.95454545 1.         1.         0.9       ]


In [43]:
print(C_V_svm) # ....overrated

[1.         0.95454545 1.         1.         1.        ]


In [45]:
print(C_V_knn)

[1.         0.95454545 0.9047619  1.         0.95      ]


In [46]:
lr.fit(X_train,Y_train)
svm.fit(X_train,Y_train)
knn.fit(X_train,Y_train)

D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [47]:
lr.score(X_test,Y_test)

0.9583333333333334

In [48]:
svm.score(X_test,Y_test)

0.9583333333333334

In [49]:
knn.score(X_test,Y_test)

0.9166666666666666

In [50]:
from sklearn.model_selection import cross_val_predict
y_pred_L=cross_val_predict(lr,X_train,Y_train,cv=5)
y_pred_svm=cross_val_predict(svm,X_train,Y_train,cv=5)
y_pred_knn=cross_val_predict(knn,X_train,Y_train,cv=5)

D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to

In [51]:
y_pred_L

array([0, 2, 0, 0, 1, 1, 2, 1, 0, 0, 2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 2, 1,
       1, 0, 0, 1, 0, 2, 2, 2, 2, 2, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 0,
       1, 2, 1, 1, 0, 2, 1, 0, 2, 1, 0, 2, 2, 0, 1, 2, 1, 2, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 2, 2, 1, 1, 0, 2, 0, 1, 0, 2, 1, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 1, 0, 0, 1, 0, 2, 2, 2, 2, 1, 0, 1, 0, 1])

In [52]:
y_pred_svm

array([0, 2, 0, 0, 1, 1, 2, 1, 0, 0, 2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 2, 1,
       1, 0, 0, 1, 0, 2, 2, 2, 2, 2, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 0,
       1, 2, 1, 1, 0, 2, 1, 0, 2, 1, 0, 2, 2, 0, 1, 2, 1, 2, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 2, 2, 1, 1, 0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 1, 0, 0, 1, 0, 2, 2, 2, 2, 1, 0, 1, 0, 1])

In [53]:
y_pred_knn

array([0, 2, 0, 0, 1, 1, 2, 1, 0, 0, 2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 2, 1,
       1, 0, 0, 1, 0, 2, 2, 2, 2, 2, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 0,
       1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 2, 2, 0, 1, 2, 1, 2, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 2, 2, 1, 1, 0, 2, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       2, 0, 0, 0, 1, 0, 0, 1, 0, 2, 2, 2, 2, 1, 0, 1, 0, 1])

In [55]:
from sklearn.ensemble import VotingClassifier
vot=VotingClassifier([("Logistic regression",lr),
                       ("KNeighbors",knn),
                       ("SVC",svm)
                        ])

In [56]:
vot.fit(X_train,Y_train)

D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


VotingClassifier(estimators=[('Logistic regression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False))...f', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=None, voting='hard', weights=None)

In [57]:
vot.score(X_train,Y_train)

1.0

In [59]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=11)
rf.fit(X_train,Y_train)
rf.score(X_train,Y_train)


1.0