What is a Python NumPy?
NumPy is a Python package which stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object, provide tools for integrating C, C++ etc. It is also useful in linear algebra, random number capability etc. NumPy array can also be used as an efficient multi-dimensional container for generic data. Now, let me tell you what exactly is a python numpy array.

NumPy Array: Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize numpy arrays from nested Python lists and access it elements. In order to perform these numpy operations, the next question which will come in your mind is:

How do I install NumPy?
To install Python NumPy, go to your command prompt and type “pip install numpy”.

In [1]:
#importing numpy package
import numpy as np

In [3]:
#Single-dimensional Numpy Array:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#Multi-dimensional Array:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [6]:
#Creating list of distance and time
distance = [12,40,50,70,100]
time = [0.27,0.54,0.77,0.55,0.29]

In [7]:
dist1 = np.array([distance])
time1 = np.array([time])

In [8]:
speed = dist1/time1
speed

array([[ 44.44444444,  74.07407407,  64.93506494, 127.27272727,
        344.82758621]])

In [9]:
#To check version
print(np.__version__)

1.16.2


In [10]:
x = np.array([1,2,3,7.8,6.7])
x

array([1. , 2. , 3. , 7.8, 6.7])

In [11]:
type(x)

numpy.ndarray

# Class and Attributes of ndarray—.ndim

Numpy’s array class is “ndarray,” also referred to as “numpy.ndarray.” The attributes of ndarrayare:

This refers to the number of axes (dimensions) of the array. It is also called the rank of the array.

In [12]:
import numpy as np 
a = np.array(1) 
print (a)

1


In [13]:
a.ndim

0

In [15]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [16]:
x.ndim

1

In [17]:
# more than one dimensions 
b = np.array([[1, 2,5], [3, 4,7]])
print (b)
b.ndim

[[1 2 5]
 [3 4 7]]


2

# ndarray.shape

This consists of a tuple of integers showing the size of the array in each dimension. The length of the “shape tuple” is the rank or ndim.

In [20]:
b.shape

(2, 3)

# ndarray.size

It gives the total number of elements in the array. It is equal to the product of the elements of the shape tuple.

In [21]:
b.size

6

# ndarray.dtype

It’s an object that describes the type of the elements in the array. It can be created or specified using Python.

In [23]:
b.dtype

dtype('int32')

In [24]:
b.itemsize

4

In [25]:
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]]
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [26]:
arr2>4

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

# Basic Operations—Example

NumPy uses the indices of the elements in each array to carry out basic operations. In this case, where we are looking at a dataset of four cyclists during two trials, vector addition of the arrays gives the required output.

In [27]:
np_first_trial_cyclist = np.array([10,12,15,16])

In [28]:
np_second_trial_cyclist = np.array([20,25,30,45])

In [29]:
np_first_trial_cyclist + np_second_trial_cyclist

array([30, 37, 45, 61])

Accessing Array Elements: Indexing

In [30]:
import numpy as np
cyclist_trial = np.array([[10,12,15,16],[20,25,30,45]])
cyclist_trial

array([[10, 12, 15, 16],
       [20, 25, 30, 45]])

In [31]:
first_trial = cyclist_trial[0]

In [32]:
first_trial

array([10, 12, 15, 16])

In [33]:
cyclist_trial


array([[10, 12, 15, 16],
       [20, 25, 30, 45]])

In [34]:
first_trial = cyclist_trial[1][0]

In [35]:
first_trial

20

In [36]:
a = cyclist_trial[1,1]
a

25

In [37]:
second_trial = cyclist_trial[:,2]
second_trial

array([15, 30])

In [38]:
cyclist_trial.shape

(2, 4)

In [39]:
third_trial = cyclist_trial[:,1:3]

In [40]:
third_trial

array([[12, 15],
       [25, 30]])

In [42]:
a = ("a","b","c","d","e","f","g","h")
x = slice(4,6)
print(a[x])

('e', 'f')


In [43]:
b = np.arange(2.5,6.5)

In [44]:
b

array([2.5, 3.5, 4.5, 5.5])

In [45]:
x = np.arange(10,21)
print(x)

[10 11 12 13 14 15 16 17 18 19 20]


In [46]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [47]:
# slice items starting from index 
a = np.arange(10)
print(a)
print (a[2:])

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [48]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print( a ) 
a.ndim
## slice items starting from index
#print ('Now we will slice the array from the index a[1:]') 
print (a[1:])
print (a[1][1])
print (a[1][1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[[3 4 5]
 [4 5 6]]
4
[4 5]


In [49]:
#The random module provides nice functions to generate random numbers (and also statistical distributions) of any given shape.

# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

# One random number between [0,1)
print(np.random.random())

# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

[[0.65648238 0.39697047]
 [0.44426585 0.97146096]]
[[ 0.3961729  -2.17563855]
 [-0.51196015  0.78663327]]
[[1 1]
 [9 2]]
0.3100360151679976
[[0.32218621 0.51746659]
 [0.33588914 0.13312045]]
