In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [56]:
dataset=pd.read_csv("bank-full.csv",sep=";")

In [57]:
dataset.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [58]:
dataset.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [59]:
X=dataset.iloc[:,0:16]

In [46]:
x=dataset[['marital', 'education']]


In [60]:
Y=dataset.iloc[:,-1]

In [61]:
dataset.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [62]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

In [63]:
X=X.values

In [64]:
for i in [1,2,3,4,6,7,8,10,15]:
    X[:,i]=lb.fit_transform(X[:,i].astype(str))


In [84]:
Y1=lb.fit_transform(Y)
Y1[:5]

array([0, 0, 0, 0, 0], dtype=int64)

In [86]:
Y1=lb.inverse_transform(Y1)
Y1[:5]

array([0, 0, 0, 0, 0])

In [87]:
lb.classes_

array([0, 1])

In [11]:
X=pd.DataFrame(X,columns=['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome'])

In [58]:
from sklearn.preprocessing import StandardScaler

In [59]:
SS=StandardScaler()

In [60]:
X_scaled=SS.fit_transform(X)

D:\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype object were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
D:\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype object were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [62]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression()

In [65]:
LR.fit(X_scaled,Y)

D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [67]:
LR.score(X,Y)

0.11930724823604875

In [69]:
LR.score(X_scaled,Y)

0.8909557408595253

In [96]:
new=np.array([[58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3]])
new.shape

(1, 16)

In [97]:
LR.predict(new)

array([1])

0         4
1         9
2         2
3         1
4        11
5         4
6         4
7         2
8         5
9         9
10        0
11        0
12        9
13        9
14        7
15        5
16        0
17        1
18        5
19        7
20        1
21        4
22        1
23        7
24        5
25        0
26        4
27        2
28        4
29        9
         ..
45181     1
45182     9
45183     5
45184     5
45185     7
45186    11
45187     7
45188     4
45189     7
45190     1
45191     5
45192     4
45193     6
45194     4
45195     5
45196     8
45197     4
45198     4
45199     1
45200     9
45201     4
45202     0
45203     8
45204     5
45205     9
45206     9
45207     5
45208     5
45209     1
45210     2
Name: job, Length: 45211, dtype: object